services:
  # Backend Service
  - type: web
    name: be-todo
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DB_HOST
        value: dpg-d81gfa5ckfvc738d9nqg-a
      - key: DB_USER
        value: todos_h9i9_user
      - key: DB_PASSWORD
        value: PmkGIyOv2Qytief6gQ0GBRlv7JIbXO0z
      - key: DB_NAME
        value: todos_h9i9
      - key: DB_PORT
        value: 5432
      - key: PORT
        value: 5000

  # Frontend Service
  - type: web
    name: fe-todo
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo.onrender.com

databases:
  - name: todo-db
    databaseName: todos_h9i9
    user: todos_h9i9_user
    plan: free