services:
  # Backend Service
  - type: web
    name: be-todo
    env: docker
    plan: free
    rootDir: A1
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: DATABASE_URL
        value: postgresql://my_todo_db_vzjq_user:CjybHWbIalaW1GcEIJBir4Vg9nCNT0bf@dpg-d7odivi8qa3s73ahr2ng-a.singapore-postgres.render.com:5432/my_todo_db_vzjq?sslmode=require
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production

  # Frontend Service
  - type: web
    name: fe-todo
    env: docker
    plan: free
    rootDir: A1
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-api.onrender.com